### ISSUE TITLE
Create main menu

### ISSUE THREAD

**Issue by Jamelle-Boose** [Jamelle-Boose/contract-creator#8]
#### Description

A main menu so the user can decide if they are done using the app. 

Options:

- Contracts
- Exit

#### Tasks

- [x] user should be welcomed at launch
- [ ] Options should be presented
- [ ] user is taken to main menu after contracts are copied to the clipboard
